baseurl = "https://dotfox.at"
title = "dotfox"
author = "Niko Ryba"
canonifyurls = true
paginate = 3
theme = "aether"
themesDir = "../../" 

[params]
    brand = "dotfox"
    description = "Web- & IT-Lösungen"
    headshotimg = "img/faceshot.jpg"

[markup]
  [markup.highlight]
    style = "igor"